### ISSUE TITLE
Building for Linux and Windows for Distribution

### ISSUE THREAD

**Issue by wwderw** [neutralinojs/neutralinojs-cli#15]
Just found this project.  Looks very promising being a slimmed down SDK for apps.

I do have a couple of question, I've got it to work fine locally, but for apps that I would like to distribute, when doing the build process.  Is there anyway that I could have the target result be an AppImage for Linux and a binary archive or single portable exe file for Windows builds?

The other question, since I work off Linux (and my typical Linux Electron dev is in a VM), is it possible to build for Windows on Linux?  If so, do we need WINE or will the CLI be able to handle things without WINE?

Thanks for the help and keep up with the project.  I've been a fan of Electron, but having an alternative be less resource intensive would be great.

**Comment by shalithasuranga** [comment]
Hey.. sorry for the late response. Please check the following answer.

neu CLI offers binaries for Linux, macOS, and Windows with the `neu build command. You can generate binaries for any supported platform from any supported platform since pre-built binaries are used. Neutralinojs app has two components: `resources.neu` and the platform-specific binary and it won't produce a single binary. It's done like that to solve various issues in auto-update and bundling.

You can check more info about distribution from the documentation: https://neutralino.js.org/docs/distribution/overview

**Comment by yulolimum** [comment]
@shalithasuranga Do you have any recommended tools for packaging the binaries + resource files? I know on a Mac one can possibly just create a `.app` folder and include both binaries there. But for other Platforms? I'm not necessarily looking for a step-by-step guide, but just a general direction using `neu build` as a starting point?
