### ISSUE TITLE
command line test not working on MacOS

### ISSUE THREAD

**Issue by yuechenw213** [neutralinojs/neutralinojs-cli#151]
when trying to run `npm test` on macOS , there is an error log
`./scripts/test_commands.sh: line 51: xvfb-run: command not found`
as I known xvfb-run is not a command for macOS, so it doesn't work

referring to #139, since it is only supposed to run on `ubuntu`, maybe disable `npm test` for other systems will bring clearer expectations to users.

**Comment by pathange-s** [comment]
As discussed earlier with other members of org, the current implementation of tests is just a temporary one. There will be a new afresh test suite implemented in mocha-assert framework, probably soon. Till then, this could be either fixed by making it compatible with macOS or stop running it on other OS (I prefer the former)

**Comment by pathange-s** [comment]
The new test suite has been under development and now has been implemented partially. You can try it out, by pulling the latest source code. Please consider closing this issue.
