### ISSUE TITLE
npm install not working for mac

### ISSUE THREAD

**Issue by M00ny0z** [neutralinojs/neutralinojs-cli#187]
Running `npm install -g @neutralinojs/neu` runs successfully with output:
```
changed 145 packages, and audited 146 packages in 2s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
But running `neu create myapp` results in `-bash: neu: command not found`

**Comment by JannikGM** [comment]
This has nothing to do with neutralinojs, so this issue should be closed.

---

It works fine for me. It depends on how you set up your npm / shell.
Obviously the folder where you install npm packages globally must be in your `PATH`.

Depending on how you installed npm, your installer will have taken care of this. Because of how many ways there are to install npm, you'll have to figure this out yourself.

Here are various solutions (some bad / dangerous, some good) to this: https://stackoverflow.com/questions/14803978/npm-global-path-prefix

**Comment by sp00ck** [comment]
and fedora linux

.npm/_npx/0214858268217ccb/node_modules/@neutralinojs/neu/src/utils.js:42
    return path?.replace(/^\//, '');
                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)

uname -a
Linux ee233 5.11.22-100.fc32.x86_64 #1 SMP Wed May 19 18:58:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pathange-s** [comment]
@M00ny0z I just checked out for the same on Mac. It works pretty fine, Can you please check and let me know if the issue persists? Close the issue in case its working fine.

**Comment by skushagra9** [comment]
yes , this is working fine 
@shalithasuranga i think you can close it

**Comment by shalithasuranga** [comment]
Thanks all for re-testing this issue, so I'll close it then :tada:
