### ISSUE TITLE
--frontend-lib-dev not working in some node versions

### ISSUE THREAD

**Issue by cer1969** [neutralinojs/neutralinojs-cli#208]
Hi
Using "**neu run --frontend-lib-dev**" on windows 11.

With node versions 18.14.2 and 18.16.0 I got this error many times until I stopped the command: 
**neu: INFO Hot reload patch was reverted.**

But this works ok with node versions 16.13.1 and 20.0.0
Any ideas why this is happening?

**Comment by ElDonad** [comment]
I have the exact same problem in Windows 10. I did a quick debug round, and found out this is caused by the CLI not being able to connect to the neutralino executable it spawned. I don't understand why this happens yet, I'll try to do a minimal test case.

**Comment by ElDonad** [comment]
Okay, found the issue ! 
In [the websocket module](https://github.com/neutralinojs/neutralinojs-cli/blob/40bb056c9d20abed7f4b080262658f87e72ac376/src/modules/websocket.js#L21), node behaves differently when given addresses with "localhost" in it. It seems that in node 18 at least (the version I tested), localhost does not get properly resolved. I've replaced it with the ipv4 loopback address (127.0.0.1) and it works without issue. 

The problem was, the patch gets applied to the frontend file only when the cli manages to connect to the backend, which it cannot do because of this bug, hence the console spam. 

I might do a PR to fix that.
